// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bidding_zone_api.AppContext;

#nullable disable

namespace bidding_zone_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bidding_zone_api.Models.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e001"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d001"),
                            Price = 160.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e002"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d001"),
                            Price = 170.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c004")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e003"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d002"),
                            Price = 310.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e004"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d003"),
                            Price = 820.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c005")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e005"),
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d004"),
                            Price = 130.00m,
                            Status = 1,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e006"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d005"),
                            Price = 260.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c004")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e007"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d006"),
                            Price = 410.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e008"),
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d007"),
                            Price = 95.00m,
                            Status = 3,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c005")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e009"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d008"),
                            Price = 210.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e010"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d009"),
                            Price = 510.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e011"),
                            CreatedAt = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d010"),
                            Price = 360.00m,
                            Status = 1,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e012"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d011"),
                            Price = 115.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c005")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e013"),
                            CreatedAt = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d012"),
                            Price = 45.00m,
                            Status = 3,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c004")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e014"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d013"),
                            Price = 75.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e015"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d014"),
                            Price = 610.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002")
                        },
                        new
                        {
                            Id = new Guid("ac4aab6e-2d5f-4d84-a3e4-6b4d0cb8e016"),
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d015"),
                            Price = 90.00m,
                            Status = 2,
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c004")
                        });
                });

            modelBuilder.Entity("bidding_zone_api.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTimer")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WinnerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d001"),
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A well preserved antique wooden chair.",
                            EndTimer = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 150.00m,
                            Status = 0,
                            Title = "Antique Wooden Chair",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d002"),
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic film camera in working condition.",
                            EndTimer = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 300.00m,
                            Status = 0,
                            Title = "Vintage Camera",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d003"),
                            CreatedAt = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightly used mountain bike, great condition.",
                            EndTimer = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 800.00m,
                            Status = 0,
                            Title = "Mountain Bike",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d004"),
                            CreatedAt = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genuine leather jacket, size medium.",
                            EndTimer = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 120.00m,
                            Status = 1,
                            Title = "Leather Jacket",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d005"),
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Six string acoustic guitar with case.",
                            EndTimer = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 250.00m,
                            Status = 0,
                            Title = "Acoustic Guitar",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d006"),
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest generation gaming console, barely used.",
                            EndTimer = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 400.00m,
                            Status = 0,
                            Title = "Gaming Console",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d007"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern glass top coffee table.",
                            EndTimer = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 90.00m,
                            Status = 2,
                            Title = "Coffee Table",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d008"),
                            CreatedAt = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sturdy wooden office desk with drawers.",
                            EndTimer = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 200.00m,
                            Status = 0,
                            Title = "Office Desk",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d009"),
                            CreatedAt = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unlocked smartphone, excellent condition.",
                            EndTimer = new DateTime(2026, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 500.00m,
                            Status = 0,
                            Title = "Smartphone",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d010"),
                            CreatedAt = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant stainless steel wristwatch.",
                            EndTimer = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 350.00m,
                            Status = 1,
                            Title = "Wristwatch",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            WinnerUserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d011"),
                            CreatedAt = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tall wooden bookshelf with five shelves.",
                            EndTimer = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 110.00m,
                            Status = 0,
                            Title = "Bookshelf",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d012"),
                            CreatedAt = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stainless steel electric kettle, fast boil.",
                            EndTimer = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 40.00m,
                            Status = 2,
                            Title = "Electric Kettle",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d013"),
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Well maintained skateboard, ready to ride.",
                            EndTimer = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 70.00m,
                            Status = 0,
                            Title = "Skateboard",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d014"),
                            CreatedAt = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Original oil painting, framed.",
                            EndTimer = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 600.00m,
                            Status = 0,
                            Title = "Painting",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c4aab6e-2d5f-4d84-a3e4-6b4d0cb8d015"),
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete set of gardening tools.",
                            EndTimer = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Image = "",
                            StartingPrice = 85.00m,
                            Status = 0,
                            Title = "Garden Tools Set",
                            UserId = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003"),
                            WinnerUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("bidding_zone_api.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Message")
                        .HasColumnType("uuid");

                    b.Property<int>("Title")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("bidding_zone_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c001"),
                            Email = "ja@gmail.com",
                            FirstName = "jack",
                            Gender = 0,
                            LastName = "phiri",
                            Password = "password"
                        },
                        new
                        {
                            Id = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c002"),
                            Email = "lewis@gmail.com",
                            FirstName = "lewis",
                            Gender = 0,
                            LastName = "moyo",
                            Password = "password"
                        },
                        new
                        {
                            Id = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c003"),
                            Email = "taza@gmail.com",
                            FirstName = "taza",
                            Gender = 0,
                            LastName = "thousand",
                            Password = "password"
                        },
                        new
                        {
                            Id = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c004"),
                            Email = "admin@gmail.com",
                            FirstName = "admin",
                            Gender = 0,
                            LastName = "admin",
                            Password = "password"
                        },
                        new
                        {
                            Id = new Guid("8c4aab6e-2d5f-4d84-a3e4-6b4d0cb8c005"),
                            Email = "ngoni@gmail.com",
                            FirstName = "ngoni",
                            Gender = 0,
                            LastName = "mathews",
                            Password = "password"
                        });
                });

            modelBuilder.Entity("bidding_zone_api.Models.User", b =>
                {
                    b.OwnsOne("bidding_zone_api.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("HouseNumber")
                                .HasColumnType("integer");

                            b1.Property<int>("Province")
                                .HasColumnType("integer");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Surbub")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
